openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/players:
    get:
      summary: Players
      description: 'Get all players (paginated, 50 per page)'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 124493
                      name: chocomint
                      score: 807
                      created_at: '2022-04-27T20:13:07.000000Z'
                      updated_at: '2022-04-27T20:13:08.000000Z'
                    -
                      id: 124493
                      name: chocomint
                      score: 807
                      created_at: '2022-04-27T20:13:07.000000Z'
                      updated_at: '2022-04-27T20:13:08.000000Z'
                  links:
                    first: '/?page=1'
                    last: '/?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: '/?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: /
                    per_page: 50
                    to: 2
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 124493
                        name: chocomint
                        score: 807
                        created_at: '2022-04-27T20:13:07.000000Z'
                        updated_at: '2022-04-27T20:13:08.000000Z'
                      -
                        id: 124493
                        name: chocomint
                        score: 807
                        created_at: '2022-04-27T20:13:07.000000Z'
                        updated_at: '2022-04-27T20:13:08.000000Z'
                    items:
                      type: object
                  links:
                    type: object
                    example:
                      first: '/?page=1'
                      last: '/?page=1'
                      prev: null
                      next: null
                  meta:
                    type: object
                    example:
                      current_page: 1
                      from: 1
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: '/?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      path: /
                      per_page: 50
                      to: 2
                      total: 2
      tags:
        - Players
      security: []
  '/api/players/{id}':
    get:
      summary: Player
      description: 'Get a player by id (same as osu player id)'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 124493
                    name: chocomint
                    score: 807
                    created_at: '2022-04-27T20:13:07.000000Z'
                    updated_at: '2022-04-27T20:13:08.000000Z'
                properties:
                  data:
                    type: object
                    example:
                      id: 124493
                      name: chocomint
                      score: 807
                      created_at: '2022-04-27T20:13:07.000000Z'
                      updated_at: '2022-04-27T20:13:08.000000Z'
      tags:
        - Players
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'player id (same as osu player id)'
        example: 124493
        required: true
        schema:
          type: integer
  /api/posts:
    get:
      summary: Posts
      description: 'Get all posts (paginated, 50 per page)'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: u3rk97
                      player_id: 5033077
                      map_artist: xi
                      map_title: 'Last Resort'
                      map_diff: 'R3m''s HEAVENLY'
                      author: Dcs2012Charlie
                      score: 170
                      ups: 172
                      downs: 2
                      silver: 0
                      gold: 0
                      platinum: 0
                      created_utc: 1649970782
                      final: 0
                      created_at: '2022-04-15T16:44:25.000000Z'
                      updated_at: '2022-04-15T16:44:25.000000Z'
                    -
                      id: u3rk97
                      player_id: 5033077
                      map_artist: xi
                      map_title: 'Last Resort'
                      map_diff: 'R3m''s HEAVENLY'
                      author: Dcs2012Charlie
                      score: 170
                      ups: 172
                      downs: 2
                      silver: 0
                      gold: 0
                      platinum: 0
                      created_utc: 1649970782
                      final: 0
                      created_at: '2022-04-15T16:44:25.000000Z'
                      updated_at: '2022-04-15T16:44:25.000000Z'
                  links:
                    first: '/?page=1'
                    last: '/?page=1'
                    prev: null
                    next: null
                  meta:
                    current_page: 1
                    from: 1
                    last_page: 1
                    links:
                      -
                        url: null
                        label: '&laquo; Previous'
                        active: false
                      -
                        url: '/?page=1'
                        label: '1'
                        active: true
                      -
                        url: null
                        label: 'Next &raquo;'
                        active: false
                    path: /
                    per_page: 50
                    to: 2
                    total: 2
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: u3rk97
                        player_id: 5033077
                        map_artist: xi
                        map_title: 'Last Resort'
                        map_diff: 'R3m''s HEAVENLY'
                        author: Dcs2012Charlie
                        score: 170
                        ups: 172
                        downs: 2
                        silver: 0
                        gold: 0
                        platinum: 0
                        created_utc: 1649970782
                        final: 0
                        created_at: '2022-04-15T16:44:25.000000Z'
                        updated_at: '2022-04-15T16:44:25.000000Z'
                      -
                        id: u3rk97
                        player_id: 5033077
                        map_artist: xi
                        map_title: 'Last Resort'
                        map_diff: 'R3m''s HEAVENLY'
                        author: Dcs2012Charlie
                        score: 170
                        ups: 172
                        downs: 2
                        silver: 0
                        gold: 0
                        platinum: 0
                        created_utc: 1649970782
                        final: 0
                        created_at: '2022-04-15T16:44:25.000000Z'
                        updated_at: '2022-04-15T16:44:25.000000Z'
                    items:
                      type: object
                  links:
                    type: object
                    example:
                      first: '/?page=1'
                      last: '/?page=1'
                      prev: null
                      next: null
                  meta:
                    type: object
                    example:
                      current_page: 1
                      from: 1
                      last_page: 1
                      links:
                        -
                          url: null
                          label: '&laquo; Previous'
                          active: false
                        -
                          url: '/?page=1'
                          label: '1'
                          active: true
                        -
                          url: null
                          label: 'Next &raquo;'
                          active: false
                      path: /
                      per_page: 50
                      to: 2
                      total: 2
      tags:
        - Posts
      security: []
  '/api/posts/{id}':
    get:
      summary: Post
      description: 'Get a post by id (same as reddit post id)'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: u3rk97
                    player_id: 5033077
                    map_artist: xi
                    map_title: 'Last Resort'
                    map_diff: 'R3m''s HEAVENLY'
                    author: Dcs2012Charlie
                    score: 170
                    ups: 172
                    downs: 2
                    silver: 0
                    gold: 0
                    platinum: 0
                    created_utc: 1649970782
                    final: 0
                    created_at: '2022-04-15T16:44:25.000000Z'
                    updated_at: '2022-04-15T16:44:25.000000Z'
                properties:
                  data:
                    type: object
                    example:
                      id: u3rk97
                      player_id: 5033077
                      map_artist: xi
                      map_title: 'Last Resort'
                      map_diff: 'R3m''s HEAVENLY'
                      author: Dcs2012Charlie
                      score: 170
                      ups: 172
                      downs: 2
                      silver: 0
                      gold: 0
                      platinum: 0
                      created_utc: 1649970782
                      final: 0
                      created_at: '2022-04-15T16:44:25.000000Z'
                      updated_at: '2022-04-15T16:44:25.000000Z'
      tags:
        - Posts
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'post id (same as reddit post id)'
        example: u3rk97
        required: true
        schema:
          type: string
  '/api/ranks/{playerId}':
    get:
      summary: Ranks
      description: 'Get the rank history for a player'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      player_id: 6447454
                      rank: 1
                      created_at: '2022-04-15T16:45:59.000000Z'
                      updated_at: '2022-04-15T16:45:59.000000Z'
                    -
                      id: 1
                      player_id: 6447454
                      rank: 1
                      created_at: '2022-04-15T16:45:59.000000Z'
                      updated_at: '2022-04-15T16:45:59.000000Z'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        player_id: 6447454
                        rank: 1
                        created_at: '2022-04-15T16:45:59.000000Z'
                        updated_at: '2022-04-15T16:45:59.000000Z'
                      -
                        id: 1
                        player_id: 6447454
                        rank: 1
                        created_at: '2022-04-15T16:45:59.000000Z'
                        updated_at: '2022-04-15T16:45:59.000000Z'
                    items:
                      type: object
      tags:
        - Ranks
      security: []
    parameters:
      -
        in: path
        name: playerId
        description: 'player id (same as osu player id)'
        example: 124493
        required: true
        schema:
          type: integer
tags:
  -
    name: Players
    description: ''
  -
    name: Posts
    description: ''
  -
    name: Ranks
    description: ''
